name: Cleanup GHCR

on:
  schedule:
    - cron: "0 20 * * 0"  # 每周日 20:00 UTC（北京时间周一 04:00）
  workflow_dispatch:
    inputs:
      keep:
        description: "Min versions to keep"
        default: "10"
        required: false

permissions:
  contents: read
  packages: write

jobs:
  prune-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged container versions
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-type: container
          package-name: ${{ github.event.repository.name }}
          delete-only-untagged-versions: true
          min-versions-to-keep: ${{ inputs.keep || '10' }}
