name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*", "*.*.*" ]
  schedule:
    - cron: "0 18 * * *" # 每日 18:00 UTC 构建（北京时间 02:00）
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (non-schedule)
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v4

      - name: Checkout master (schedule)
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: prep
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_LOWER}"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG="${{ github.ref_name }}"
          else
            TAG="latest"
          fi
          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tags=${IMAGE}:${TAG}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
